### ISSUE TITLE
路径不管怎么改都有问题萌新求解？

### ISSUE THREAD

**Issue by NeuralBiophysics** [yusanshi/pdf_image_binarization#2]
<img width="740" alt="屏幕截图 2022-07-25 174002" src="https://user-images.githubusercontent.com/109410449/180747454-c4853fc0-2398-4371-9f43-19104ef3381c.png">

**Comment by yusanshi** [comment]
写成 `C:/Users/....` 这样的形式呢？

**Comment by NeuralBiophysics** [comment]
> 写成 这样的形式呢？`C:/Users/....`

<img width="558" alt="屏幕截图 2022-07-25 182452" src="https://user-images.githubusercontent.com/109410449/180755629-2709ae8c-d09a-4a3f-8f32-16ee69551b34.png">

**Comment by NeuralBiophysics** [comment]
还是not a file

**Comment by yusanshi** [comment]
是不是文件不存在，这个相对地址输的正确吗？

**Comment by NeuralBiophysics** [comment]
我是直接ctrl+a 复制的文件地址怎么可能不存在呢

**Comment by NeuralBiophysics** [comment]
请问您能运行吗?我能把文件发给你帮我处理一下吗？我折腾了五个小时已经快疯了。

**Comment by yusanshi** [comment]
私发我邮箱吧，只能帮跑一次哦

**Comment by NeuralBiophysics** [comment]
我找到知乎上有一个参照你这个写的，他的版本用了新的库，可能是版本问题我用的他的跑出来了，应该是pip版本不同下载的库不兼容，不过还是很感谢您的回答，谢谢。
